name: localization_example
description: A demo app for the anas_localization package
publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  anas_localization:
    path: ..

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
