name: anas_localization
description: >
  A Flutter/Dart package for easy and flexible localization, supporting
  multiple languages, custom dictionaries, runtime language switching,
  and integration with Flutter's localization features. Includes code generation
  tools and asset management for scalable internationalization.
version: 1.0.0
homepage: https://github.com/Melsaeed276/anas_localization

repository: https://github.com/Melsaeed276/anas_localization
issue_tracker: https://github.com/Melsaeed276/anas_localization/issues
documentation: https://github.com/Melsaeed276/anas_localization#readme

topics:
  - flutter
  - localization
  - internationalization
  - l10n
  - language

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.0 <1.0.0" # Required for date/time and number formatting features

  # We should not use any other 3rd state management. Avoid version conflicts.
  # provider: ^6.1.5

  shared_preferences: ">=2.0.0 <3.0.0"

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  localization_gen: localization_gen

flutter:
  assets:
    - assets/lang/
